### ISSUE TITLE
122A Solution Error

### ISSUE THREAD

**Issue by Onkar755** [mohandsakr/my-problem-solving-solutions-on-codeforces.com#5]
Index out of bound error in problem 122A while traversing through the array of lucky numbers in the second solution

**Comment by mohandsakr** [comment]
Share your solution please.
Please note:
My solution is on c++not java .

**Comment by Onkar755** [comment]
on line 45 there is a while loop with condition (a[i] <= 777) it is showing following error
**runtime error: index 14 out of bounds for type 'int [14]'**
so change the condition to (i < 14)

`#include <bits/stdc++.h>
using namespace std;

int main(){
    
    int a[] = {4, 7, 44, 47, 74, 77, 444, 447, 474, 477, 744, 747, 774, 777};
    int n; 
    cin >> n;
    int i = 0;
    
    while(i < 14){
        if(n % a[i] == 0){
            cout << "YES" << endl;
            return 0;
        }
        i++;
    }
    cout<<"NO";
    return 0;
}  `

**Comment by Onkar755** [comment]
on line 45 there is a while loop with condition (a[i] <= 777) it is showing following error
runtime error: index 14 out of bounds for type 'int [14]'
so change the condition to (i < 14)

`#include <bits/stdc++.h>
using namespace std;
int main(){
    int a[] = {4, 7, 44, 47, 74, 77, 444, 447, 474, 477, 744, 747, 774, 777};
    int n; 
    cin >> n;
    int i = 0;
    while(i < 14){
        if(n % a[i] == 0){
            cout << "YES" << endl;
            return 0;
        }
        i++;
    }
    cout<<"NO";
    return 0;
} `

**Comment by Onkar755** [comment]
```
#include <bits/stdc++.h>
using namespace std;
int main(){
    int a[] = {4, 7, 44, 47, 74, 77, 444, 447, 474, 477, 744, 747, 774, 777};
    int n; 
    cin >> n;
    int i = 0;
    while(i < 14){
        if(n % a[i] == 0){
            cout << "YES" << endl;
            return 0;
        }
        i++;
    }
    cout<<"NO";
    return 0;
} 
```

**Comment by Onkar755** [comment]
change in condition of while loop
